apiVersion: batch/v1
kind: Job
metadata:
  name: install-kruise-pre-install
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
      - name: helm-install-kruise
        image: alpine/helm:latest
        command: 
        - /bin/sh
        - -c
        - |
          helm repo add openkruise https://openkruise.github.io/charts/
          helm repo update
          helm install kruise openkruise/kruise --version 1.4.0
          # Add a loop to check if kruise CRDs are ready if needed
      restartPolicy: OnFailure
