name: Release Charts
on:
  push:
    branches:
    - master

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    # New step to add Helm repo
    - name: Add Helm Repositories
      run: |
        helm repo add openkruise https://openkruise.github.io/charts/
        helm repo update

    # Build dependencies
    - name: Build chart dependencies
      run: |
        cd charts/kvrocks-operator
        helm dependency build

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
