name: Release Charts
on:
  push:
    branches:
    - master

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Add Helm Repositories
      run: |
        helm repo add openkruise https://openkruise.github.io/charts/

    - name: Build chart dependencies
      run: |
        cd charts/kvrocks-operator
        helm dependency update

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
